on:
  push:
    branches:
      -master
name: Production Deploy
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        ftp-server: ftp://109.123.246.76
        ftp-username: admin_nafiz
        ftp-password: ${{ secrets.prod_FTP_PASSWORD }}